-- Generated by `jwc migrate new`. Do not edit.
-- 1786512984_init
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 1 · schemas and types ──
CREATE SCHEMA IF NOT EXISTS public;

-- ── 2 · tables and columns ──
CREATE TABLE public.api_call (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path varchar(200) NOT NULL,
    method varchar(8) NOT NULL,
    status integer NOT NULL,
    latency_ms integer NOT NULL,
    latency_us integer NOT NULL,
    ts timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_api_call PRIMARY KEY (id)
);
CREATE TABLE public.link (
    code varchar(8) NOT NULL,
    url varchar(2048) NOT NULL,
    hits integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_link PRIMARY KEY (code)
);

-- ── 3 · data ──
-- jwc:data 1786512984_init
-- A `1786512984_init.data.sql` sidecar, if present, is applied here
-- (migrations.md §7.2). It is hand-written and never generated.

-- ── 5 · indexes ──
CREATE INDEX ix_api_call__ts
    ON public.api_call (ts);

-- ── 7 · comments ──
COMMENT ON TABLE public.api_call IS 'One logged request. Written from `MetricsTracker`''s `after` block, so
the row carries the status and the duration the client actually saw.';
COMMENT ON COLUMN public.api_call.latency_ms IS 'Whole milliseconds, kept because a deploy can land either side of
the migration that added the microsecond column. `GET /` answers in
well under a millisecond, so across 1.48M logged requests this
recorded min 0, max 1, mean 0.00 — measured, and useless for a
percentile.';
COMMENT ON TABLE public.link IS 'One short link. `code` is the slug in the short URL and the primary
key: the redirect is a single lookup on it, which is the hot path.';

COMMIT;
