-- Generated by `jwc migrate new`. Do not edit.
-- 1786512985_add_hits_index
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 5 · indexes ──
CREATE INDEX ix_link__hits
    ON public.link (hits);

COMMIT;
