-- Generated by `jwc migrate new`. Do not edit.
-- down of 1786512985_add_hits_index
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 9 · destructive ──
DROP INDEX public.ix_link__hits;

COMMIT;
