-- Generated by `jwc migrate new`. Do not edit.
-- down of 1786512984_init
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 9 · destructive ──
DROP TABLE public.api_call;
DROP TABLE public.link;

COMMIT;
